<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class IssuesSeeder extends Seeder
{
    public function run(): void
    {
        $issues = [
            // ── IDEOLOGI
            [
                'judul'        => 'Penyebaran konten radikal via platform terenkripsi meningkat di Jawa Timur',
                'deskripsi'    => 'Terdeteksi peningkatan signifikan distribusi konten bernuansa radikal melalui aplikasi pesan terenkripsi.',
                'kategori'     => 'ideologi',
                'sub_kategori' => 'radikalisme',
                'risiko'       => 'tinggi',
                'status'       => 'aktif',
                'wilayah'      => 'Jawa Timur',
                'sumber'       => 'Laporan Internal',
                'created_at'   => Carbon::now()->subDays(0),
                'updated_at'   => Carbon::now(),
            ],
            [
                'judul'        => 'Kelompok separatis baru teridentifikasi di wilayah perbatasan Papua',
                'deskripsi'    => 'Ditemukan kelompok baru yang diduga memiliki agenda separatis di wilayah perbatasan.',
                'kategori'     => 'ideologi',
                'sub_kategori' => 'separatisme',
                'risiko'       => 'tinggi',
                'status'       => 'aktif',
                'wilayah'      => 'Papua',
                'sumber'       => 'Laporan Lapangan',
                'created_at'   => Carbon::now()->subDays(1),
                'updated_at'   => Carbon::now(),
            ],
            [
                'judul'        => 'Rekrutmen anggota baru kelompok ekstremis di media sosial',
                'deskripsi'    => 'Aktivitas rekrutmen terdeteksi aktif di beberapa platform media sosial.',
                'kategori'     => 'ideologi',
                'sub_kategori' => 'ekstremisme',
                'risiko'       => 'tinggi',
                'status'       => 'aktif',
                'wilayah'      => 'Jawa Barat',
                'sumber'       => 'Pemantauan Digital',
                'created_at'   => Carbon::now()->subDays(2),
                'updated_at'   => Carbon::now(),
            ],
            [
                'judul'        => 'Propaganda ideologi radikal ditemukan di lingkungan kampus',
                'deskripsi'    => 'Material propaganda ditemukan beredar di beberapa kampus negeri.',
                'kategori'     => 'ideologi',
                'sub_kategori' => 'radikalisme',
                'risiko'       => 'sedang',
                'status'       => 'aktif',
                'wilayah'      => 'DI Yogyakarta',
                'sumber'       => 'Laporan Mitra',
                'created_at'   => Carbon::now()->subDays(3),
                'updated_at'   => Carbon::now(),
            ],
            [
                'judul'        => 'Indikasi jaringan separatis lintas provinsi',
                'deskripsi'    => 'Ditemukan pola komunikasi yang mengindikasikan jaringan terorganisir lintas provinsi.',
                'kategori'     => 'ideologi',
                'sub_kategori' => 'separatisme',
                'risiko'       => 'tinggi',
                'status'       => 'aktif',
                'wilayah'      => 'Sulawesi',
                'sumber'       => 'Intelijen',
                'created_at'   => Carbon::now()->subDays(4),
                'updated_at'   => Carbon::now(),
            ],
            [
                'judul'        => 'Ceramah bermuatan ekstremisme beredar di platform video',
                'deskripsi'    => 'Video ceramah yang memuat konten ekstremisme viral di YouTube dan Telegram.',
                'kategori'     => 'ideologi',
                'sub_kategori' => 'ekstremisme',
                'risiko'       => 'sedang',
                'status'       => 'aktif',
                'wilayah'      => 'Nasional',
                'sumber'       => 'Pemantauan Digital',
                'created_at'   => Carbon::now()->subDays(5),
                'updated_at'   => Carbon::now(),
            ],
            [
                'judul'        => 'Peningkatan aktivitas sel tidur jaringan radikal',
                'deskripsi'    => 'Terpantau peningkatan komunikasi internal sel tidur yang sebelumnya tidak aktif.',
                'kategori'     => 'ideologi',
                'sub_kategori' => 'radikalisme',
                'risiko'       => 'tinggi',
                'status'       => 'aktif',
                'wilayah'      => 'Jawa Tengah',
                'sumber'       => 'Intelijen',
                'created_at'   => Carbon::now()->subDays(6),
                'updated_at'   => Carbon::now(),
            ],

            // ── POLITIK
            [
                'judul'        => 'Indikasi kampanye disinformasi menjelang Pilkada 2026 di 4 provinsi',
                'deskripsi'    => 'Ditemukan pola kampanye disinformasi yang terkoordinasi menjelang pilkada.',
                'kategori'     => 'politik',
                'sub_kategori' => 'elektoral',
                'risiko'       => 'tinggi',
                'status'       => 'aktif',
                'wilayah'      => 'Nasional',
                'sumber'       => 'Pemantauan Digital',
                'created_at'   => Carbon::now()->subDays(0),
                'updated_at'   => Carbon::now(),
            ],
            [
                'judul'        => 'Pertemuan aktor asing dengan figur oposisi terpantau di Jakarta',
                'deskripsi'    => 'Terpantau serangkaian pertemuan antara diplomat asing tidak resmi dengan tokoh oposisi.',
                'kategori'     => 'politik',
                'sub_kategori' => 'intervensi_asing',
                'risiko'       => 'sedang',
                'status'       => 'aktif',
                'wilayah'      => 'Jakarta',
                'sumber'       => 'Laporan Lapangan',
                'created_at'   => Carbon::now()->subDays(1),
                'updated_at'   => Carbon::now(),
            ],
            [
                'judul'        => 'Dugaan pembelian suara di daerah pemilihan Sumatera Utara',
                'deskripsi'    => 'Laporan dari lapangan mengindikasikan praktik pembelian suara terorganisir.',
                'kategori'     => 'politik',
                'sub_kategori' => 'elektoral',
                'risiko'       => 'tinggi',
                'status'       => 'aktif',
                'wilayah'      => 'Sumatera Utara',
                'sumber'       => 'Laporan Mitra',
                'created_at'   => Carbon::now()->subDays(2),
                'updated_at'   => Carbon::now(),
            ],
            [
                'judul'        => 'Gerakan oposisi terorganisir meningkat jelang sidang parlemen',
                'deskripsi'    => 'Terpantau peningkatan koordinasi kelompok oposisi menjelang sidang paripurna.',
                'kategori'     => 'politik',
                'sub_kategori' => 'oposisi',
                'risiko'       => 'sedang',
                'status'       => 'aktif',
                'wilayah'      => 'Jakarta',
                'sumber'       => 'Laporan Internal',
                'created_at'   => Carbon::now()->subDays(3),
                'updated_at'   => Carbon::now(),
            ],
            [
                'judul'        => 'Pendanaan kampanye dari sumber asing tidak terverifikasi',
                'deskripsi'    => 'Ditemukan aliran dana kampanye yang diduga bersumber dari entitas asing.',
                'kategori'     => 'politik',
                'sub_kategori' => 'intervensi_asing',
                'risiko'       => 'tinggi',
                'status'       => 'aktif',
                'wilayah'      => 'Jawa Barat',
                'sumber'       => 'Analisis Keuangan',
                'created_at'   => Carbon::now()->subDays(4),
                'updated_at'   => Carbon::now(),
            ],

            // ── EKONOMI
            [
                'judul'        => 'Dugaan aliran dana ilegal ke rekening yayasan proyek infrastruktur Kalimantan',
                'deskripsi'    => 'Terdeteksi aliran dana mencurigakan ke rekening yayasan yang terkait proyek infrastruktur.',
                'kategori'     => 'ekonomi',
                'sub_kategori' => 'korupsi',
                'risiko'       => 'tinggi',
                'status'       => 'aktif',
                'wilayah'      => 'Kalimantan',
                'sumber'       => 'Analisis Keuangan',
                'created_at'   => Carbon::now()->subDays(0),
                'updated_at'   => Carbon::now(),
            ],
            [
                'judul'        => 'Investasi asing di sektor pertambangan tanpa izin lengkap terdeteksi',
                'deskripsi'    => 'Ditemukan perusahaan asing beroperasi di sektor strategis tanpa kelengkapan izin.',
                'kategori'     => 'ekonomi',
                'sub_kategori' => 'investasi_asing',
                'risiko'       => 'sedang',
                'status'       => 'aktif',
                'wilayah'      => 'Sulawesi',
                'sumber'       => 'Laporan Lapangan',
                'created_at'   => Carbon::now()->subDays(1),
                'updated_at'   => Carbon::now(),
            ],
            [
                'judul'        => 'Indikasi pencucian uang melalui transaksi properti di Bali',
                'deskripsi'    => 'Pola transaksi properti tidak wajar yang mengindikasikan praktik pencucian uang.',
                'kategori'     => 'ekonomi',
                'sub_kategori' => 'pencucian_uang',
                'risiko'       => 'sedang',
                'status'       => 'aktif',
                'wilayah'      => 'Bali',
                'sumber'       => 'Analisis Keuangan',
                'created_at'   => Carbon::now()->subDays(2),
                'updated_at'   => Carbon::now(),
            ],
            [
                'judul'        => 'Pejabat daerah diduga terima suap proyek jalan nasional',
                'deskripsi'    => 'Laporan dugaan suap dalam proses tender proyek infrastruktur jalan nasional.',
                'kategori'     => 'ekonomi',
                'sub_kategori' => 'korupsi',
                'risiko'       => 'tinggi',
                'status'       => 'aktif',
                'wilayah'      => 'Sumatera Selatan',
                'sumber'       => 'Laporan Mitra',
                'created_at'   => Carbon::now()->subDays(3),
                'updated_at'   => Carbon::now(),
            ],

            // ── SOSBUD
            [
                'judul'        => 'Ketegangan antarumat beragama meningkat pasca-insiden di Sulawesi Tengah',
                'deskripsi'    => 'Terpantau peningkatan ketegangan sosial pasca insiden yang melibatkan komunitas berbeda agama.',
                'kategori'     => 'sosbud',
                'sub_kategori' => 'komunal',
                'risiko'       => 'tinggi',
                'status'       => 'aktif',
                'wilayah'      => 'Sulawesi Tengah',
                'sumber'       => 'Laporan Lapangan',
                'created_at'   => Carbon::now()->subDays(0),
                'updated_at'   => Carbon::now(),
            ],
            [
                'judul'        => 'Narasi hoaks soal kebijakan pemerintah viral di TikTok dan Telegram',
                'deskripsi'    => 'Konten hoaks menyebar dengan cepat dan berpotensi memicu keresahan sosial.',
                'kategori'     => 'sosbud',
                'sub_kategori' => 'hoaks_sara',
                'risiko'       => 'sedang',
                'status'       => 'aktif',
                'wilayah'      => 'Nasional',
                'sumber'       => 'Pemantauan Digital',
                'created_at'   => Carbon::now()->subDays(1),
                'updated_at'   => Carbon::now(),
            ],
            [
                'judul'        => 'Provokasi SARA di media sosial menjelang hari besar keagamaan',
                'deskripsi'    => 'Terdeteksi konten provokatif bernuansa SARA yang meningkat menjelang hari besar.',
                'kategori'     => 'sosbud',
                'sub_kategori' => 'hoaks_sara',
                'risiko'       => 'tinggi',
                'status'       => 'aktif',
                'wilayah'      => 'Nasional',
                'sumber'       => 'Pemantauan Digital',
                'created_at'   => Carbon::now()->subDays(2),
                'updated_at'   => Carbon::now(),
            ],
            [
                'judul'        => 'Konflik komunal antar kelompok etnis di perbatasan Kalimantan',
                'deskripsi'    => 'Terpantau eskalasi konflik berbasis etnis di wilayah perbatasan antar provinsi.',
                'kategori'     => 'sosbud',
                'sub_kategori' => 'komunal',
                'risiko'       => 'sedang',
                'status'       => 'aktif',
                'wilayah'      => 'Kalimantan',
                'sumber'       => 'Laporan Lapangan',
                'created_at'   => Carbon::now()->subDays(3),
                'updated_at'   => Carbon::now(),
            ],

            // ── HANKAM
            [
                'judul'        => 'Serangan siber terhadap infrastruktur BSSN terdeteksi',
                'deskripsi'    => 'Serangan siber terkoordinasi terdeteksi menargetkan sistem infrastruktur kritis.',
                'kategori'     => 'hankam',
                'sub_kategori' => 'siber',
                'risiko'       => 'tinggi',
                'status'       => 'aktif',
                'wilayah'      => 'Jakarta',
                'sumber'       => 'Laporan Teknis',
                'created_at'   => Carbon::now()->subDays(0),
                'updated_at'   => Carbon::now(),
            ],
            [
                'judul'        => 'Peningkatan aktivitas vessel asing di perairan ZEE Natuna Utara',
                'deskripsi'    => 'Terpantau peningkatan frekuensi kapal asing memasuki zona ekonomi eksklusif.',
                'kategori'     => 'hankam',
                'sub_kategori' => 'perbatasan',
                'risiko'       => 'tinggi',
                'status'       => 'aktif',
                'wilayah'      => 'Kepulauan Riau',
                'sumber'       => 'Laporan Maritim',
                'created_at'   => Carbon::now()->subDays(1),
                'updated_at'   => Carbon::now(),
            ],
            [
                'judul'        => 'Jaringan pendanaan terorisme lintas negara terdeteksi aktif',
                'deskripsi'    => 'Aliran dana yang terhubung dengan kelompok teroris internasional terdeteksi masuk ke Indonesia.',
                'kategori'     => 'hankam',
                'sub_kategori' => 'terorisme',
                'risiko'       => 'tinggi',
                'status'       => 'aktif',
                'wilayah'      => 'Nasional',
                'sumber'       => 'Intelijen',
                'created_at'   => Carbon::now()->subDays(2),
                'updated_at'   => Carbon::now(),
            ],
            [
                'judul'        => 'Kebocoran data instansi pemerintah akibat serangan ransomware',
                'deskripsi'    => 'Serangan ransomware berhasil membobol sistem data salah satu instansi pemerintah pusat.',
                'kategori'     => 'hankam',
                'sub_kategori' => 'siber',
                'risiko'       => 'tinggi',
                'status'       => 'aktif',
                'wilayah'      => 'Jakarta',
                'sumber'       => 'Laporan Teknis',
                'created_at'   => Carbon::now()->subDays(3),
                'updated_at'   => Carbon::now(),
            ],
        ];

        DB::table('issues')->insert($issues);
    }
};